[build]
  command = "npm run build"
  publish = "dist"

[dev]
  command = "npm run dev"
  port = 8888
  targetPort = 8081
  publish = "dist"

# Functions are handled automatically by Netlify

[functions]
  directory = "netlify/functions" 